# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set workdir
WORKDIR /app

# Copy only necessary files
COPY main.py weather-demo.py .
COPY finance/ ./finance/

# Install required dependencies
RUN pip install --no-cache-dir httpx>=0.28.1 mcp[cli]>=1.6.0 python-dotenv

# Default to stdio transport on launch
CMD ["python", "main.py"]
